
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - openstack.stable.sap.cc
  resources:
  - openstackseeds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.stable.sap.cc
  resources:
  - openstackseeds/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.stable.sap.cc
  resources:
  - openstackseeds/status
  verbs:
  - get
  - patch
  - update
